//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCardTableID { get; set; }
        public string CustomerID { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> ProcessDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CR_deposit__or_DR_withdrawl_ { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
